### ISSUE TITLE
Architect commands with multiple targets cannot specify overrides: Lint issues

### ISSUE THREAD

**Issue by hamzahamidi** [gothinkster/angular-realworld-example-app#116]
When trying to commit I'm facing this issue:
> Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: ang2-conduit,ang2-conduit-e2e
Error: Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: ang2-conduit,ang2-conduit-e2e
    at LintCommand.validate (/home/hamza/projects/angular-realworld-example-app/node_modules/@angular/cli/models/architect-command.js:83:23)
    at Object.<anonymous> (/home/hamza/projects/angular-realworld-example-app/node_modules/@angular/cli/models/command-runner.js:134:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hamza/projects/angular-realworld-example-app/node_modules/@angular/cli/models/command-runner.js:11:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:

**Comment by lankaapura** [comment]
@hamzahamidi remove linting is not the fix. Pls check the answer here https://stackoverflow.com/a/51179794

**Comment by hamzahamidi** [comment]
Thank you @lankaapura  The fix was to change the lint line to:
```
"lint": "ng lint --force ang2-conduit ang2-conduit-e2e",

**Comment by hamzahamidi** [comment]
@EricSimons can you take a look a this issue & the PR#116 please?
