### ISSUE TITLE
Project Start issue (need help urgent)

### ISSUE THREAD

**Issue by subratbhola** [gothinkster/angular-realworld-example-app#138]
When Hitting 'ng serve', i getting below compilation issue: 

this._workspace.getProjectTargets is not a function
TypeError: this._workspace.getProjectTargets is not a function
    at rxjs_1.forkJoin._workspace.listProjectNames.map.projectName (E:\angularReal\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:71:66)
    at Array.map (<anonymous>)
    at MergeMapSubscriber.rxjs_1.forkJoin.pipe.operators_1.concatMap [as project] (E:\angularReal\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:70:78)
    at MergeMapSubscriber._tryNext (E:\angularReal\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (E:\angularReal\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (E:\angularReal\node_modules\rxjs\internal\Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (E:\angularReal\node_modules\rxjs\internal\observable\forkJoin.js:79:25)
    at InnerSubscriber._complete (E:\angularReal\node_modules\rxjs\internal\InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (E:\angularReal\node_modules\rxjs\internal\Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (E:\angularReal\node_modules\rxjs\internal\Subscriber.js:94:26)

Can you please tell me what i am missing.

**Comment by benmed00** [comment]
Same Problem Her

![image](https://user-images.githubusercontent.com/17787436/55689222-46cd7000-5982-11e9-8c4f-eef0781a28a4.png)
